spring:
  cloud:
    gateway:
      routes:
        - id: good_route
          uri: http://localhost:8443
          predicates:
          - Path=/goods/**
  application:
    name: GATEWAY
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080